package com.ubs.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Central point for obtaining a JDBC connection to the embedded SQLite
 * database and for making sure the required schema exists.
 *
 * The database file is created (if absent) in the working directory as
 * "usage_billing.db". All DAO classes obtain connections through this
 * class rather than talking to DriverManager directly.
 */
public final class DatabaseManager {

    private static final String DB_FILE = "usage_billing.db";
    private static final String URL = "jdbc:sqlite:" + DB_FILE;

    private static boolean initialized = false;

    private DatabaseManager() {
        // utility class
    }

    /** Returns a new connection to the SQLite database, with foreign keys enabled. */
    public static synchronized Connection getConnection() throws SQLException {
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException e) {
            throw new SQLException("SQLite JDBC driver not found on classpath", e);
        }
        Connection conn = DriverManager.getConnection(URL);
        try (Statement st = conn.createStatement()) {
            st.execute("PRAGMA foreign_keys = ON");
        }
        return conn;
    }

    /**
     * Returns the row id generated by the most recent INSERT on this
     * connection. The bundled SQLite JDBC driver does not reliably support
     * PreparedStatement.getGeneratedKeys(), so every DAO retrieves the new
     * primary key this way instead (SQLite's own last_insert_rowid()).
     */
    public static int lastInsertId(Connection conn) throws SQLException {
        try (Statement st = conn.createStatement();
             java.sql.ResultSet rs = st.executeQuery("SELECT last_insert_rowid()")) {
            return rs.next() ? rs.getInt(1) : -1;
        }
    }

    /** Creates all required tables if they do not already exist. Safe to call multiple times. */
    public static synchronized void initializeSchema() {
        if (initialized) {
            return;
        }
        String createResources =
            "CREATE TABLE IF NOT EXISTS resources (" +
            "  id INTEGER PRIMARY KEY AUTOINCREMENT," +
            "  name TEXT NOT NULL UNIQUE," +
            "  category TEXT," +
            "  capacity INTEGER NOT NULL CHECK(capacity > 0)," +
            "  created_at TEXT NOT NULL" +
            ")";

        String createServices =
            "CREATE TABLE IF NOT EXISTS services (" +
            "  id INTEGER PRIMARY KEY AUTOINCREMENT," +
            "  resource_id INTEGER NOT NULL," +
            "  service_name TEXT NOT NULL," +
            "  first_hour_price REAL NOT NULL CHECK(first_hour_price >= 0)," +
            "  additional_hour_price REAL NOT NULL CHECK(additional_hour_price >= 0)," +
            "  FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE CASCADE" +
            ")";

        String createUsageSessions =
            "CREATE TABLE IF NOT EXISTS usage_sessions (" +
            "  id INTEGER PRIMARY KEY AUTOINCREMENT," +
            "  resource_id INTEGER NOT NULL," +
            "  service_id INTEGER NOT NULL," +
            "  user_name TEXT NOT NULL," +
            "  start_time TEXT NOT NULL," +
            "  end_time TEXT," +
            "  status TEXT NOT NULL DEFAULT 'ACTIVE'," +
            "  FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE CASCADE," +
            "  FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE" +
            ")";

        String createBills =
            "CREATE TABLE IF NOT EXISTS bills (" +
            "  id INTEGER PRIMARY KEY AUTOINCREMENT," +
            "  session_id INTEGER NOT NULL," +
            "  resource_name TEXT NOT NULL," +
            "  service_name TEXT NOT NULL," +
            "  user_name TEXT NOT NULL," +
            "  start_time TEXT NOT NULL," +
            "  end_time TEXT NOT NULL," +
            "  duration_minutes INTEGER NOT NULL," +
            "  billed_hours INTEGER NOT NULL," +
            "  amount REAL NOT NULL," +
            "  generated_at TEXT NOT NULL," +
            "  FOREIGN KEY (session_id) REFERENCES usage_sessions(id) ON DELETE CASCADE" +
            ")";

        try (Connection conn = getConnection(); Statement st = conn.createStatement()) {
            st.execute(createResources);
            st.execute(createServices);
            st.execute(createUsageSessions);
            st.execute(createBills);
            initialized = true;
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize database schema", e);
        }
    }
}
